name: Build and publish image

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build --tag samcre/awskubectl:latest .

      - name: Login to DockerHub Registry
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: echo ${DOCKER_TOKEN} | docker login -u ${DOCKER_USERNAME} --password-stdin

      - name: Docker Publish
        uses: manusa/actions-publish-docker@v1.0.1
        with:
          name: samcre/awskubectl
          tag: latest
